namespace: telecom

image:
  repository: docker.io/karthikmd06/telecom-customer-insights
  tag: "1.0.0" # default, can be overwritten by ArgoCD Image Updater
  pullPolicy: IfNotPresent
  pullSecrets:
    - name: dockerhub

replicaCount: 2

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

env:
  CUSTOMER_DATA: "/data/customers.csv"

secrets:
  enabled: true
  name: telecom-app-secrets
  data:
    APP_SECRET: "changeme"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

# ---------------------------
# PVC configuration
# ---------------------------
pvc:
  enabled: true
  name: data-lake-pvc
  storageClassName: "microk8s-hostpath"
  accessModes:
    - ReadWriteOnce
  size: 1Gi

# ---------------------------
# CronJob configuration
# ---------------------------
cronjob:
  enabled: true
  schedule: "0 * * * *"  # every hour
  rows: 5000
  outputPath: "/data/customers.csv"
