apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metabase
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: metabase
      targetRevision: 7.3.3
      helm:
        releaseName: metabase
        valueFiles:
          - $values/charts/telecom/data-lake-infra/metabase/values.yaml
    - repoURL: https://github.com/mkarthikd/Python-base-webapp.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: data-lake
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
