# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: postgres
#   namespace: argocd
# spec:
#   project: default
#   sources:
#     - repoURL: https://charts.bitnami.com/bitnami
#       chart: postgresql
#       targetRevision: 15.5.11
#       helm:
#         releaseName: postgres
#         valueFiles:
#           - $values/charts/telecom/data-lake-infra/postgres/values.yaml
#     - repoURL: https://github.com/mkarthikd/Python-base-webapp.git
#       targetRevision: main
#       ref: values
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: data-lake
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
#       - ApplyOutOfSyncOnly=true

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mkarthikd/Python-base-webapp.git
    targetRevision: main
    path: charts/telecom/data-lake-infra/postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: data-lake
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
