apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trino
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://trinodb.github.io/charts
      chart: trino
      targetRevision: 0.13.0
      helm:
        releaseName: trino
        valueFiles:
          - $values/charts/telecom/data-lake-infra/trino/values.yaml
    - repoURL: https://github.com/mkarthikd/Python-base-webapp.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: data-lake
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
