apiVersion: apps/v1
kind: Deployment
metadata:
  name: telecom-api
  namespace: telecom
spec:
  replicas: 2
  selector:
    matchLabels:
      app: telecom-api
  template:
    metadata:
      labels:
        app: telecom-api
    spec:
      containers:
        - name: telecom-api
          image: telecom-customer-insights:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: CUSTOMER_DATA
              value: "/data/customers.csv"
          volumeMounts:
            - name: customer-data
              mountPath: /data
      volumes:
        - name: customer-data
          emptyDir: {}
