apiVersion: v1
kind: Service
metadata:
  name: telecom-api
  namespace: telecom
spec:
  selector:
    app: telecom-api
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http
