apiVersion: v1
kind: ConfigMap
metadata:
  name: load-csv-scripts
  namespace: {{ .Values.namespace }}
data:
  load_csv.py: |
    import pandas as pd
    from sqlalchemy import create_engine
    import os

    CUSTOMER_DATA = os.environ.get("CUSTOMER_DATA", "/data/customers.csv")
    POSTGRES_URL = os.environ.get("POSTGRES_URL")

    if os.path.exists(CUSTOMER_DATA):
        df = pd.read_csv(CUSTOMER_DATA)
        engine = create_engine(POSTGRES_URL)
        df.to_sql("customers", engine, if_exists="replace", index=False)
        print(f"Loaded {len(df)} rows into PostgreSQL 'customers'")
    else:
        print(f"{CUSTOMER_DATA} not found, skipping DB load")
