apiVersion: v1
kind: Service
metadata:
  name: telecom-api
  namespace: {{ .Values.namespace }}
  labels:
    app: telecom-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: telecom-api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
