persistence:
  enabled: true
  size: 1Gi
  storageClass: microk8s-hostpath

service:
  type: LoadBalancer

livenessProbe:
  enabled: true
  initialDelaySeconds: 120
  periodSeconds: 20
  failureThreshold: 6

readinessProbe:
  enabled: true
  initialDelaySeconds: 120
  periodSeconds: 20
  failureThreshold: 6
