apiVersion: v1
kind: Service
metadata:
  name: postgres-lb
  namespace: data-lake
spec:
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    cnpg.io/cluster: postgres
    role: primary
