apiVersion: v1
kind: Secret
metadata:
  name: postgres-app-secret
  namespace: data-lake
type: Opaque
stringData:
  username: iceberg
  password: icebergpass
  superuser: postgres
  superuser-password: AdminPass123
