# values.yaml

auth:
  # Application-level user
  username: iceberg
  password: icebergpass
  database: iceberg

  # Superuser for admin tasks
  postgresSuperuser: true
  superuserUsername: admin
  superuserPassword: AdminPass123

primary:
  persistence:
    enabled: true
    size: 2Gi
    storageClass: microk8s-hostpath
